wrt = input("Enter text to write to the file: ")
file_1 = open('output.txt' , 'w')
file_1.write(wrt + "\n")
file_1.close()
print("Data succesfully written to output.txt")

app = input("\nEnter additional text to append: ")
file_1 = open('output.txt' , 'a')
file_1.write(app)
file_1.close()
print("Data successfully appended\n \nFinal content of output.txt")
file_1 = open('output.txt' , 'r')
reading_file = file_1.read()
print(reading_file)
file_1.close()
